parameters:
    # Uploads directory
    uploads_directory: '%kernel.project_dir%/public/files/uploads'
    # Uploaded file final folders
    pictures_images_directory: '%kernel.project_dir%/public/files/images/pictures'
    videos_images_directory: '%kernel.project_dir%/public/files/images/videos'
    music_directory: '%kernel.project_dir%/public/files/music'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    #App\Service\FileUploader:
    #    arguments:
    #        $pictures_images_directory: '%pictures_images_directory%'
    #        $videos_images_directory: '%videos_images_directory%'
    #        $music_directory: '%music_directory%'
    #       
    #App\EventSubscriber\EntitySubscriber:
    #    tags:
    #        - { name: 'doctrine.event_subscriber' }
